//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sales_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
